[theme]

# Warna utama untuk komponen interaktif (tombol, slider, dll)
primaryColor="#0c58a4"

# Warna latar belakang utama aplikasi
backgroundColor="#FFFFFF"

# Warna latar belakang sekunder (misalnya untuk sidebar)
secondaryBackgroundColor="#d6e4e1"

# Warna teks utama
textColor="#0f1116"

# Jenis font yang digunakan
font="sans serif"